name: Sample Application License Scan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  license-scan:
    name: Scan (open-source) licenses
    uses: ./.github/workflows/_license-check.yml
    with:
      working-directory: './samples/basic/SimpleConsoleApplication'